# Generated by Django 6.0.4 on 2026-04-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('sudan', 'Sudan'), ('uk', 'United Kingdom')], default='uk', max_length=10),
        ),
    ]
