# Generated by Django 6.0.4 on 2026-04-12 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200)),
                ('amount_sdg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt', models.FileField(upload_to='receipts/')),
                ('ocr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ocr_match', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
