# Generated by Django 6.0.4 on 2026-04-15 23:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_exchangerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='rate_used',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_gets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='total_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sdg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('invested_sdg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_at_submission', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gbp_at_submission', models.DecimalField(decimal_places=4, max_digits=10)),
                ('period_months', models.IntegerField(choices=[(6, '6 Months'), (9, '9 Months'), (12, '1 Year')])),
                ('start_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('cashed_out', 'Cashed Out'), ('reinvested', 'Reinvested')], default='active', max_length=20)),
                ('rate_at_maturity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('gbp_at_maturity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('gain_loss_gbp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reinvested_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvested_from', to='transfers.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('due_soon', 'Payment Due Soon'), ('matured', 'Investment Matured')], default='due_soon', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transfers.investment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
